### ISSUE TITLE
Typo in code's blog post

### ISSUE THREAD

**Issue by Kuzcoo** [eatonphil/pj#2]
Hello,

The article you wrote is great, very easy to follow.
I just caught a little error here:

```python
 json_null, string = lex_null(string)
        if json_null is not None:
            tokens.append(json_null)
            continue
```

`lex_null()`, returns `True` so I guess you should append `None` as you did in the code here on github.

**Comment by eatonphil** [comment]
Ah that is a great point. Thank you! Just fixed it https://github.com/eatonphil/eatonphil.com/commit/d0b691bc1cf1f794122ca7c127a4a7882470bdd8.
